name: onPush.yaml
on: [workflow_dispatch, push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello fellas"
      - run: node --version
